-- Seed roadmap skills (idempotent: clear then insert)
truncate public.skill_progress cascade;
truncate public.roadmap_skills cascade;

insert into public.roadmap_skills (phase, category, title, description, drill_hint, sort_order) values
  (1, 'technique', 'Reliable forehand & backhand from mid-court', 'Clean contact and directional control under moderate pace — the base for every other shot.', 'Cross-court rallies focusing on height over the net and depth.', 1),
  (1, 'technique', 'Serve consistency (first ball in)', 'Get 80%+ first serves in with a clear target (body / T / wide) rather than pace.', 'Bucket serves: 20 to each target zone before adding spin.', 2),
  (1, 'technique', 'Return patterns — deep and neutral', 'Neutralise strong serves; avoid floaters that invite smash.', 'Return to the server’s feet / middle, then recover to ready.', 3),
  (1, 'technique', 'Bandeja basics', 'Defensive-offensive overhead that keeps you at net without forcing winners.', 'Lob feed → bandeja cross-court, recover split-step.', 4),
  (1, 'technique', 'Víbora introduction', 'Side-spin overhead to open the court; distinguish when bandeja vs víbora.', 'Shadow + soft feed focusing on grip and contact point.', 5),
  (1, 'technique', 'Wall defence — back glass', 'Read bounce off glass; stay balanced and rebuild the rally.', 'Partner feeds deep; you play off glass to lob or rebuild.', 6),
  (1, 'tactics', 'Court positioning & diamond shape', 'Know your side, cover the middle, and move as a unit with your partner.', 'Video one club set; mark where you stood on each point.', 7),
  (1, 'tactics', 'When to lob vs drive', 'Use lob to reset net pressure; drive when opponents are deep.', 'Constraint game: only lob when both opponents are at net.', 8),
  (1, 'physical', 'Aerobic base for long sessions', 'Handle 90–120 min court blocks without technique collapse.', '2× zone-2 cardio sessions (bike/run) of 30–40 min weekly.', 9),
  (1, 'physical', 'Shoulder & rotator cuff resilience', 'Protect overhead volume — critical for bandeja/víbora longevity.', 'Band external rotations + face pulls 3×/week.', 10),
  (1, 'physical', 'Lateral agility & split-step', 'Explode to wide balls and recover to centre.', 'Ladder + lateral bounds before court sessions.', 11),
  (1, 'mental', 'Point-by-point reset', 'Drop the last error; play the next ball with a clear intention.', 'After every point, say one cue word before the next serve.', 12),
  (1, 'competition', 'Northampton club match rhythm', 'Play regular club sets locally — build match toughness before travelling.', 'Book 1–2 competitive club sessions per week at your home club.', 13),
  (1, 'competition', 'First club / box league events', 'Enter low-stakes local events to learn formats, scoring pressure, and partnering.', 'Target one club box or social tournament this quarter.', 14),
  (1, 'mental', 'Warm-up routine you own', 'Same 10–12 min activation every session so competition feels familiar.', 'Write and stick to a fixed warm-up checklist.', 15),
  (2, 'technique', 'Aggressive vibora & smash selection', 'Finish short lobs; know when to kill vs keep pressure.', 'Feed high balls; decide kill / vibora / bandeja in under 1s.', 1),
  (2, 'technique', 'Chiquita & low volleys', 'Keep balls at opponents’ feet from the net to force weak replies.', 'Soft feed to feet; aim for second bounce before service line.', 2),
  (2, 'technique', 'Counter-lob under pressure', 'Survive smash pressure with height and depth, not panic.', 'Partner smashes; you only counter-lob deep cross.', 3),
  (2, 'tactics', 'Serve + 1 patterns', 'Plan the first two shots of every point with your partner.', 'Pre-agree three serve+1 patterns and use only those in a set.', 4),
  (2, 'tactics', 'Exploiting the weaker opponent', 'Identify and pressure the lower-level player without tunnel vision.', 'Post-match note: who did you target and did it work?', 5),
  (2, 'tactics', 'Switching & poaching communication', 'Verbal cues and trust so you cover middle without collisions.', 'Practice ‘mine/yours/switch’ calls in every warm-up point.', 6),
  (2, 'physical', 'Periodised gym — strength block', 'Lower-body and rotational power for tournament weeks.', '2 strength sessions focusing squat/hinge/rotational med-ball.', 7),
  (2, 'physical', 'In-season recovery discipline', 'Sleep, mobility, and load management when playing multiple events/month.', 'Log recovery every tournament weekend; protect Monday rest.', 8),
  (2, 'mental', 'Competitive partner chemistry', 'Fixed or semi-fixed partner for ranking events; shared language and roles.', 'Agree roles (server patterns, who takes middle) before each event.', 9),
  (2, 'mental', 'Handling bad calls & momentum swings', 'Stay process-focused when a set flips 2–2 to 2–5.', 'Timeout routine: breath + one tactical adjust + next point cue.', 10),
  (2, 'competition', 'Midlands regional tournament circuit', 'Travel within the Midlands for stronger opposition and ranking exposure.', 'Plan a quarterly Midlands event calendar from Northampton.', 11),
  (2, 'competition', 'LTA / national ranking event entries', 'Start collecting national ranking points; learn draw formats and seeding.', 'Enter first graded national event; note ranking points earned.', 12),
  (2, 'competition', 'Trajectory toward UK top 300–150', 'Track ranking after each event; set volume targets for points.', 'Update UK ranking in Profile after every ranking list refresh.', 13),
  (2, 'technique', 'Transition defence → net', 'Move forward as a pair after a deep lob or weak reply.', 'Constraint: after every successful lob, both must reach net.', 14),
  (3, 'competition', 'National calendar volume', 'Consistent national events — points come from volume + deep runs.', 'Block 1–2 national weekends per month in season.', 1),
  (3, 'competition', 'Push into UK top 100', 'Secondary goal: crack the UK top 100 through ranking events and results.', 'Set milestone ranks (200 → 150 → 100) with target dates.', 2),
  (3, 'competition', 'FIP Promotion / Rise pathway awareness', 'Understand entry criteria, wildcards, and qualifying routes for first FIP event.', 'Research next accessible FIP Promotion; note entry window.', 3),
  (3, 'competition', 'First FIP points', 'Primary goal: earn your first official FIP ranking points.', 'Peak for one target FIP event; taper gym the week before.', 4),
  (3, 'tactics', 'Peak-week tournament templates', 'Know exactly what court, gym, and recovery look like 7 days out.', 'Write a peak-week checklist and reuse it for every A-event.', 5),
  (3, 'tactics', 'Scouting stronger pairs', 'Watch top UK pairs’ patterns; adapt returns and lob height.', 'Film or note one top-100 pair’s serve+1 each month.', 6),
  (3, 'technique', 'High-percentage finishing under fatigue', 'Convert short balls late in third sets without spraying.', 'End practice with ‘finish 8/10’ short-ball challenges.', 7),
  (3, 'technique', 'Variety: bajada, drop, and change of pace', 'Break rhythm against ranked opponents who have seen your stock game.', 'Add one ‘chaos’ set per week with forced variety.', 8),
  (3, 'physical', 'Tournament-ready conditioning', 'Repeat high-intensity efforts across multi-match days.', 'Court-specific intervals: 4× 4-min high effort, 2-min easy.', 9),
  (3, 'physical', 'Injury prevention under load', 'Manage shoulder, knee, and lower-back load across a national calendar.', 'Weekly physio/mobility block non-negotiable in season.', 10),
  (3, 'mental', 'Big-match routines', 'Pre-match visualisation, partner huddle, and emotional regulation.', 'Same arrival timeline for every ranking final / FIP day.', 11),
  (3, 'mental', 'Long-horizon patience', 'Trust the 3-year arc — ranking climbs are noisy week to week.', 'Monthly review: process metrics over single results.', 12);
