-- Seed roadmap skills (idempotent: clear then insert)
-- Prefer this for fresh local DBs. Production: use migrations/006_padel_shots.sql instead.
truncate public.skill_progress cascade;
truncate public.roadmap_skills cascade;

insert into public.roadmap_skills (phase, category, title, description, drill_hint, sort_order) values
  -- Phase 1
  (1, 'technique', 'Reliable forehand & backhand from mid-court', 'Clean contact and directional control under moderate pace — the base for every other shot.', 'Cross-court rallies focusing on height over the net and depth.', 1),
  (1, 'technique', 'Serve consistency (first ball in)', 'Get 80%+ first serves in with a clear target (body / T / wide) rather than pace.', 'Bucket serves: 20 to each target zone before adding spin.', 2),
  (1, 'technique', 'Return patterns — deep and neutral', 'Neutralise strong serves; avoid floaters that invite smash.', 'Return to the server’s feet / middle, then recover to ready.', 3),
  (1, 'technique', 'Lob — height, depth, and disguise', 'Build a reliable defensive and offensive lob; hide intent until late so opponents can’t camp under it.', 'Feed mid-court; lob cross and down the line aiming for the back glass.', 4),
  (1, 'technique', 'Volley fundamentals (forehand & backhand)', 'Compact punch volleys at the net — block pace, take early, and keep the ball low.', 'Partner feeds soft then firm; volley to feet then recover split-step.', 5),
  (1, 'technique', 'Bandeja basics', 'Defensive-offensive overhead that keeps you at net without forcing winners.', 'Lob feed → bandeja cross-court, recover split-step.', 6),
  (1, 'technique', 'Víbora introduction', 'Side-spin overhead to open the court; distinguish when bandeja vs víbora.', 'Shadow + soft feed focusing on grip and contact point.', 7),
  (1, 'technique', 'Wall defence — back glass', 'Read bounce off glass; stay balanced and rebuild the rally.', 'Partner feeds deep; you play off glass to lob or rebuild.', 8),
  (1, 'technique', 'Wall defence — side / parallel glass', 'Handle balls that skim or bounce off the side wall without opening the middle.', 'Feed parallel; take side-wall balls early or after bounce to a safe lob/rebuild.', 9),
  (1, 'tactics', 'Court positioning & diamond shape', 'Know your side, cover the middle, and move as a unit with your partner.', 'Video one club set; mark where you stood on each point.', 10),
  (1, 'tactics', 'When to lob vs drive', 'Use lob to reset net pressure; drive when opponents are deep.', 'Constraint game: only lob when both opponents are at net.', 11),
  (1, 'physical', 'Aerobic base for long sessions', 'Handle 90–120 min court blocks without technique collapse.', '2× zone-2 cardio sessions (bike/run) of 30–40 min weekly.', 12),
  (1, 'physical', 'Shoulder & rotator cuff resilience', 'Protect overhead volume — critical for bandeja/víbora longevity.', 'Band external rotations + face pulls 3×/week.', 13),
  (1, 'physical', 'Lateral agility & split-step', 'Explode to wide balls and recover to centre.', 'Ladder + lateral bounds before court sessions.', 14),
  (1, 'mental', 'Point-by-point reset', 'Drop the last error; play the next ball with a clear intention.', 'After every point, say one cue word before the next serve.', 15),
  (1, 'competition', 'Northampton club match rhythm', 'Play regular club sets locally — build match toughness before travelling.', 'Book 1–2 competitive club sessions per week at your home club.', 16),
  (1, 'competition', 'First club / box league events', 'Enter low-stakes local events to learn formats, scoring pressure, and partnering.', 'Target one club box or social tournament this quarter.', 17),
  (1, 'mental', 'Warm-up routine you own', 'Same 10–12 min activation every session so competition feels familiar.', 'Write and stick to a fixed warm-up checklist.', 18),
  -- Phase 2
  (2, 'technique', 'Flat smash (remate) — finish short lobs', 'Kill high, short lobs with a flat overhead when the bounce-out or putaway is on.', 'Soft lob feed into the service box; aim 8/10 winners without spraying long.', 1),
  (2, 'technique', 'Kick smash — topspin bounce-out', 'Topspin overhead that kicks high off the back glass so opponents can’t rebuild.', 'Brush up on contact; aim deep middle so the ball jumps over the fence/glass.', 2),
  (2, 'technique', 'Rulo / gancho — around-the-head finish', 'Slice/hook overhead from a closed or awkward shoulder position when a flat smash isn’t available.', 'Feed slightly behind you; rulo cross-court and recover without over-rotating.', 3),
  (2, 'technique', 'Aggressive vibora & overhead selection', 'Choose bandeja vs víbora vs flat vs kick vs rulo in under a second — pressure without forced errors.', 'Mixed high-ball feeds; call the shot before contact, then execute.', 4),
  (2, 'technique', 'Bajada — attack from deep after the bounce', 'Drive or cut aggressively from the back after the ball bounces (often off glass) to seize the initiative.', 'Deep feed off glass; take a bajada to the feet or open court, then move forward.', 5),
  (2, 'technique', 'Chiquita & low volleys', 'Keep balls at opponents’ feet from the net to force weak replies.', 'Soft feed to feet; aim for second bounce before service line.', 6),
  (2, 'technique', 'Drop shot (dejarla)', 'Soft touch that dies at the net — punish deep opponents and break rhythm.', 'From mid-court after a high ball, drop short cross; only when they are deep.', 7),
  (2, 'technique', 'Counter-lob under pressure', 'Survive smash pressure with height and depth, not panic.', 'Partner smashes; you only counter-lob deep cross.', 8),
  (2, 'technique', 'Transition defence → net', 'Move forward as a pair after a deep lob or weak reply.', 'Constraint: after every successful lob, both must reach net.', 9),
  (2, 'tactics', 'Serve + 1 patterns', 'Plan the first two shots of every point with your partner.', 'Pre-agree three serve+1 patterns and use only those in a set.', 10),
  (2, 'tactics', 'Exploiting the weaker opponent', 'Identify and pressure the lower-level player without tunnel vision.', 'Post-match note: who did you target and did it work?', 11),
  (2, 'tactics', 'Switching & poaching communication', 'Verbal cues and trust so you cover middle without collisions.', 'Practice ‘mine/yours/switch’ calls in every warm-up point.', 12),
  (2, 'physical', 'Periodised gym — strength block', 'Lower-body and rotational power for tournament weeks.', '2 strength sessions focusing squat/hinge/rotational med-ball.', 13),
  (2, 'physical', 'In-season recovery discipline', 'Sleep, mobility, and load management when playing multiple events/month.', 'Log recovery every tournament weekend; protect Monday rest.', 14),
  (2, 'mental', 'Competitive partner chemistry', 'Fixed or semi-fixed partner for ranking events; shared language and roles.', 'Agree roles (server patterns, who takes middle) before each event.', 15),
  (2, 'mental', 'Handling bad calls & momentum swings', 'Stay process-focused when a set flips 2–2 to 2–5.', 'Timeout routine: breath + one tactical adjust + next point cue.', 16),
  (2, 'competition', 'Midlands regional tournament circuit', 'Travel within the Midlands for stronger opposition and ranking exposure.', 'Plan a quarterly Midlands event calendar from Northampton.', 17),
  (2, 'competition', 'LTA / national ranking event entries', 'Start collecting national ranking points; learn draw formats and seeding.', 'Enter first graded national event; note ranking points earned.', 18),
  (2, 'competition', 'Trajectory toward UK top 300–150', 'Track ranking after each event; set volume targets for points.', 'Update UK ranking in Profile after every ranking list refresh.', 19),
  -- Phase 3
  (3, 'competition', 'National calendar volume', 'Consistent national events — points come from volume + deep runs.', 'Block 1–2 national weekends per month in season.', 1),
  (3, 'competition', 'Push into UK top 100', 'Secondary goal: crack the UK top 100 through ranking events and results.', 'Set milestone ranks (200 → 150 → 100) with target dates.', 2),
  (3, 'competition', 'FIP Promotion / Rise pathway awareness', 'Understand entry criteria, wildcards, and qualifying routes for first FIP event.', 'Research next accessible FIP Promotion; note entry window.', 3),
  (3, 'competition', 'First FIP points', 'Primary goal: earn your first official FIP ranking points.', 'Peak for one target FIP event; taper gym the week before.', 4),
  (3, 'tactics', 'Peak-week tournament templates', 'Know exactly what court, gym, and recovery look like 7 days out.', 'Write a peak-week checklist and reuse it for every A-event.', 5),
  (3, 'tactics', 'Scouting stronger pairs', 'Watch top UK pairs’ patterns; adapt returns and lob height.', 'Film or note one top-100 pair’s serve+1 each month.', 6),
  (3, 'technique', 'Salida de pared — attack after the glass', 'Turn wall defence into offence: step in after the bounce and drive or lob with intent.', 'Deep smash feed; play off glass then immediately attack the next ball.', 7),
  (3, 'technique', 'High-percentage finishing under fatigue', 'Convert short balls late in third sets without spraying — choose the right finish shot.', 'End practice with ‘finish 8/10’ short-ball challenges (flat / kick / rulo).', 8),
  (3, 'technique', 'Shot variety & change of pace', 'Mix bandeja, víbora, bajada, drop, and smash options so ranked opponents can’t sit on one pattern.', 'Add one ‘chaos’ set per week with forced variety — no two identical finishes.', 9),
  (3, 'physical', 'Tournament-ready conditioning', 'Repeat high-intensity efforts across multi-match days.', 'Court-specific intervals: 4× 4-min high effort, 2-min easy.', 10),
  (3, 'physical', 'Injury prevention under load', 'Manage shoulder, knee, and lower-back load across a national calendar.', 'Weekly physio/mobility block non-negotiable in season.', 11),
  (3, 'mental', 'Big-match routines', 'Pre-match visualisation, partner huddle, and emotional regulation.', 'Same arrival timeline for every ranking final / FIP day.', 12),
  (3, 'mental', 'Long-horizon patience', 'Trust the 3-year arc — ranking climbs are noisy week to week.', 'Monthly review: process metrics over single results.', 13);
